<?xml version="1.0" encoding="utf-8"?><Database Name="Electronic" Class="electronicDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=CAMEO\SQLEXPRESS;Initial Catalog=Electronic;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ElectronicConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DiaChiKH" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienThoaiKH" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="KHACHHANG_DONDATHANG" Member="DONDATHANGs" ThisKey="MaKH" OtherKey="MAKH" Type="DONDATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.AD" Member="ADs">
    <Type Name="AD">
      <Column Name="idadmin" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="passadmin" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTHD" Member="CTHDs">
    <Type Name="CTHD">
      <Column Name="MaDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="DONDATHANG_CTHD" Member="DONDATHANG" ThisKey="MaDH" OtherKey="MADH" Type="DONDATHANG" IsForeignKey="true" />
      <Association Name="SP_CTHD" Member="SP" ThisKey="MaDH" OtherKey="MaSP" Type="SP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANG1s">
    <Type Name="KHACHHANG1">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DiaChiKH" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienThoaiKH" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="KHACHHANG1_DONDATHANG" Member="DONDATHANGs" ThisKey="MaKH" OtherKey="MAKH" Type="DONDATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.DONDATHANG" Member="DONDATHANGs">
    <Type Name="DONDATHANG">
      <Column Name="MADH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TinhTrangGiaoHang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MAKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DONDATHANG_CTHD" Member="CTHDs" ThisKey="MADH" OtherKey="MaDH" Type="CTHD" />
      <Association Name="KHACHHANG_DONDATHANG" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MaKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="KHACHHANG1_DONDATHANG" Member="KHACHHANG1" ThisKey="MAKH" OtherKey="MaKH" Type="KHACHHANG1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="MaCV" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SP" Member="SPs">
    <Type Name="SP">
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HinhSP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SLTon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MATH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SP_CTHD" Member="CTHDs" ThisKey="MaSP" OtherKey="MaDH" Type="CTHD" />
      <Association Name="SP_THUONGHIEU" Member="THUONGHIEU" ThisKey="MaSP" OtherKey="MATH" Type="THUONGHIEU" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.THUONGHIEU" Member="THUONGHIEUs">
    <Type Name="THUONGHIEU">
      <Column Name="MATH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENTH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="SP_THUONGHIEU" Member="SP" ThisKey="MATH" OtherKey="MaSP" Type="SP" IsForeignKey="true" />
    </Type>
  </Table>
</Database>